export const Clients = [
  {
    restaurant_name: 'Witting-McGlynn',
    owner_name: 'Hillard Lenormand',
    number: '2731790000',
    location: 'PO Box 26299',
  },
  {
    restaurant_name: 'Ratke Group',
    owner_name: 'Hy Harmes',
    number: '4628900497',
    location: null,
  },
  {
    restaurant_name: 'Zulauf-Kris',
    owner_name: 'Ellie Tesseyman',
    number: '8011480911',
    location: null,
  },
  {
    restaurant_name: "O'Connell, Klocko and Corkery",
    owner_name: 'Marsha Butterfield',
    number: '8991787870',
    location: null,
  },
  {
    restaurant_name: 'Fritsch LLC',
    owner_name: 'Clementius Flageul',
    number: '1897848917',
    location: null,
  },
  {
    restaurant_name: 'Ledner-Blanda',
    owner_name: 'Iosep Adelsberg',
    number: '4078551036',
    location: null,
  },
  {
    restaurant_name: 'Mann Inc',
    owner_name: 'Paige Tudball',
    number: '2156528148',
    location: 'Suite 2',
  },
  {
    restaurant_name: 'Russel, DuBuque and Rice',
    owner_name: 'Nanette Roft',
    number: '6282251815',
    location: '4th Floor',
  },
  {
    restaurant_name: 'McKenzie-Ondricka',
    owner_name: 'Jinny Gibby',
    number: '9224529368',
    location: null,
  },
  {
    restaurant_name: 'Senger-Ullrich',
    owner_name: 'Arnaldo Payfoot',
    number: '3073312178',
    location: null,
  },
  {
    restaurant_name: 'Wolff-Ziemann',
    owner_name: 'Emmie Ettels',
    number: '2325331768',
    location: null,
  },
  {
    restaurant_name: 'Kulas Group',
    owner_name: 'Kelsi Scoates',
    number: '9105101454',
    location: 'PO Box 11554',
  },
  {
    restaurant_name: 'Schaden, Wiza and Durgan',
    owner_name: 'Herculie Platt',
    number: '7153157497',
    location: null,
  },
  {
    restaurant_name: 'Kuhlman-Konopelski',
    owner_name: 'Mateo Harcarse',
    number: '9896168590',
    location: 'Suite 7',
  },
  {
    restaurant_name: 'Murray-Runolfsson',
    owner_name: 'Diann Burgise',
    number: '2536173321',
    location: 'Suite 44',
  },
  {
    restaurant_name: 'Batz-Shanahan',
    owner_name: 'Abby Cruse',
    number: '8637355088',
    location: 'Room 1627',
  },
  {
    restaurant_name: 'West-Brakus',
    owner_name: 'Raye Conneau',
    number: '2785590641',
    location: null,
  },
  {
    restaurant_name: 'McLaughlin, Bailey and Donnelly',
    owner_name: 'Torin McClements',
    number: '9232848062',
    location: 'Suite 70',
  },
  {
    restaurant_name: 'Fadel, Oberbrunner and Wilkinson',
    owner_name: 'Wendye Clement',
    number: '4841565864',
    location: null,
  },
  {
    restaurant_name: 'Klocko-Bahringer',
    owner_name: 'Giles Wennam',
    number: '2208808654',
    location: 'PO Box 87312',
  },
  {
    restaurant_name: "O'Conner, Gerlach and Feest",
    owner_name: 'Leoine Rowthorn',
    number: '4454038829',
    location: null,
  },
  {
    restaurant_name: 'Hirthe Inc',
    owner_name: 'Betsy Wilshaw',
    number: '6792763997',
    location: 'Room 1864',
  },
  {
    restaurant_name: 'Smitham, Padberg and King',
    owner_name: 'Giulia Yurocjkin',
    number: '7825014297',
    location: null,
  },
  {
    restaurant_name: 'Wintheiser, Kemmer and Parisian',
    owner_name: 'Georgine Jest',
    number: '1221401827',
    location: '16th Floor',
  },
  {
    restaurant_name: 'Stamm, Wolf and Bergstrom',
    owner_name: 'Karim White',
    number: '9648881147',
    location: '4th Floor',
  },
  {
    restaurant_name: 'Farrell-Daugherty',
    owner_name: 'Elisha Laycock',
    number: '4118269103',
    location: 'Apt 995',
  },
  {
    restaurant_name: 'Robel Group',
    owner_name: "Maxwell O'Flynn",
    number: '4688863947',
    location: 'PO Box 18881',
  },
  {
    restaurant_name: 'Abernathy-Kiehn',
    owner_name: 'Perren Cluer',
    number: '5612396183',
    location: 'Room 365',
  },
  {
    restaurant_name: 'Schmeler-Parisian',
    owner_name: 'Rollins Bohills',
    number: '6085495198',
    location: 'Suite 66',
  },
  {
    restaurant_name: 'Ankunding-Roberts',
    owner_name: 'Robbie Saltrese',
    number: '4146650262',
    location: null,
  },
  {
    restaurant_name: 'Mitchell, Huel and Mills',
    owner_name: 'Nessa Marieton',
    number: '2026080879',
    location: '4th Floor',
  },
  {
    restaurant_name: 'Grimes-Cormier',
    owner_name: 'Novelia Lackner',
    number: '6713390538',
    location: 'Suite 25',
  },
  {
    restaurant_name: 'Jacobson LLC',
    owner_name: 'Nadeen Abrahmovici',
    number: '4182525738',
    location: null,
  },
  {
    restaurant_name: 'Kling, Boyer and Bahringer',
    owner_name: 'Lynnell Eddie',
    number: '7202008056',
    location: null,
  },
  {
    restaurant_name: 'Kutch Inc',
    owner_name: 'Florence Talby',
    number: '7826195680',
    location: '5th Floor',
  },
  {
    restaurant_name: 'Swaniawski-Von',
    owner_name: 'Jason Bracknall',
    number: '8059384731',
    location: null,
  },
  {
    restaurant_name: 'Waters Group',
    owner_name: 'Dario Kennifeck',
    number: '2716543187',
    location: null,
  },
  {
    restaurant_name: 'Wisozk, Heller and Hagenes',
    owner_name: 'Giffer Linden',
    number: '1624378529',
    location: '9th Floor',
  },
  {
    restaurant_name: 'Stoltenberg-Boyer',
    owner_name: 'Gilbertine Radeliffe',
    number: '4191742515',
    location: 'Room 1599',
  },
  {
    restaurant_name: 'Konopelski-Kertzmann',
    owner_name: 'Rozalin Khidr',
    number: '9232840389',
    location: null,
  },
  {
    restaurant_name: 'Will and Sons',
    owner_name: 'Clerissa Lintall',
    number: '8791164360',
    location: null,
  },
  {
    restaurant_name: 'Yundt, Kuphal and Bins',
    owner_name: 'Kennan Clampett',
    number: '4873966193',
    location: 'Apt 1747',
  },
  {
    restaurant_name: 'Kuvalis-Breitenberg',
    owner_name: 'Vicki Sentinella',
    number: '7489056121',
    location: null,
  },
  {
    restaurant_name: 'Von LLC',
    owner_name: 'Kipp Ladlow',
    number: '7857674348',
    location: 'Suite 60',
  },
  {
    restaurant_name: 'Breitenberg-Veum',
    owner_name: 'Titos Roundtree',
    number: '3896772951',
    location: 'PO Box 43421',
  },
  {
    restaurant_name: 'Cassin, Gibson and Sipes',
    owner_name: 'Darci Taree',
    number: '3357175305',
    location: null,
  },
  {
    restaurant_name: 'Klein, Morar and Goyette',
    owner_name: 'Sandy Tieman',
    number: '3905168697',
    location: null,
  },
  {
    restaurant_name: 'Feeney Inc',
    owner_name: 'Karmen Paula',
    number: '1414169833',
    location: null,
  },
  {
    restaurant_name: 'Farrell-Hodkiewicz',
    owner_name: 'Wilbert Schwerin',
    number: '3033808024',
    location: null,
  },
  {
    restaurant_name: 'Stracke Group',
    owner_name: 'Ermin Gallagher',
    number: '1361971977',
    location: null,
  },
  {
    restaurant_name: 'Mohr-Jast',
    owner_name: 'Tucker Janes',
    number: '9996961921',
    location: null,
  },
  {
    restaurant_name: 'Robel-Zboncak',
    owner_name: 'Konrad Yarrall',
    number: '3617299458',
    location: 'Room 1159',
  },
  {
    restaurant_name: 'Hudson, Goldner and Schultz',
    owner_name: 'Boy Vagg',
    number: '1014884954',
    location: 'Apt 119',
  },
  {
    restaurant_name: 'Bogan, Weimann and Ullrich',
    owner_name: 'Maxim Elstub',
    number: '3236738820',
    location: null,
  },
  {
    restaurant_name: 'Bogisich and Sons',
    owner_name: 'Marieann McElroy',
    number: '9136224490',
    location: null,
  },
  {
    restaurant_name: 'Smith-Nolan',
    owner_name: 'Davy Vereker',
    number: '1841078869',
    location: null,
  },
  {
    restaurant_name: 'Beier-Ernser',
    owner_name: 'Amargo Greatbatch',
    number: '9721012862',
    location: null,
  },
  {
    restaurant_name: 'Swaniawski LLC',
    owner_name: 'Sasha Sweetnam',
    number: '9795254695',
    location: '20th Floor',
  },
  {
    restaurant_name: 'Bruen Inc',
    owner_name: 'Abagail Scolts',
    number: '9976160063',
    location: 'Room 1521',
  },
  {
    restaurant_name: 'Lesch-Reynolds',
    owner_name: 'Kayla Huitson',
    number: '3905528197',
    location: null,
  },
  {
    restaurant_name: 'Jaskolski, Yost and Turner',
    owner_name: 'Bebe Dudgeon',
    number: '2278151965',
    location: 'Room 386',
  },
  {
    restaurant_name: 'Ullrich-Buckridge',
    owner_name: 'Erin Handke',
    number: '5091471994',
    location: 'Room 1160',
  },
  {
    restaurant_name: 'Schumm-Walker',
    owner_name: 'Stern Castanie',
    number: '1479056003',
    location: 'Suite 70',
  },
  {
    restaurant_name: 'Wehner Group',
    owner_name: 'Khalil Velez',
    number: '8611377177',
    location: 'Suite 67',
  },
  {
    restaurant_name: 'Steuber Inc',
    owner_name: 'Susy Danbi',
    number: '9424631939',
    location: 'Suite 10',
  },
  {
    restaurant_name: 'Quitzon, Champlin and Bode',
    owner_name: 'Granthem Cantero',
    number: '9697416776',
    location: 'Room 1121',
  },
  {
    restaurant_name: 'Gottlieb, Nicolas and Strosin',
    owner_name: 'David St. Queintain',
    number: '3425200264',
    location: null,
  },
  {
    restaurant_name: 'Bruen Inc',
    owner_name: 'Ciro Henricsson',
    number: '5494632111',
    location: 'Room 22',
  },
  {
    restaurant_name: 'Hudson-Feeney',
    owner_name: 'Kylila Davidsson',
    number: '6476776782',
    location: null,
  },
  {
    restaurant_name: 'Kohler LLC',
    owner_name: 'Myrtle Ruoss',
    number: '9787376800',
    location: null,
  },
  {
    restaurant_name: 'Altenwerth Group',
    owner_name: 'Rebekah Field',
    number: '3008190549',
    location: 'Suite 23',
  },
  {
    restaurant_name: 'Kemmer Group',
    owner_name: 'Bendicty Kibby',
    number: '4322601494',
    location: null,
  },
  {
    restaurant_name: 'Zulauf-Veum',
    owner_name: 'Mohandas Hulburd',
    number: '9048558307',
    location: 'Room 485',
  },
  {
    restaurant_name: 'Feil Group',
    owner_name: 'Mendie Devine',
    number: '5174724997',
    location: null,
  },
  {
    restaurant_name: 'Mann Inc',
    owner_name: 'Benedikt MacGillicuddy',
    number: '6458203530',
    location: 'Suite 26',
  },
  {
    restaurant_name: 'Cruickshank-Ondricka',
    owner_name: 'Peg Kilminster',
    number: '8918197685',
    location: null,
  },
  {
    restaurant_name: 'White Inc',
    owner_name: 'Cristina Etheridge',
    number: '5777775173',
    location: 'Room 1372',
  },
  {
    restaurant_name: 'Kshlerin, Waelchi and Goldner',
    owner_name: 'Bronson Gillon',
    number: '7715552195',
    location: null,
  },
  {
    restaurant_name: 'Nitzsche-Daniel',
    owner_name: 'Pam Crinson',
    number: '3611228969',
    location: 'PO Box 99283',
  },
  {
    restaurant_name: 'Witting LLC',
    owner_name: 'Ephrem Cleal',
    number: '9889595243',
    location: null,
  },
  {
    restaurant_name: 'Heidenreich Inc',
    owner_name: 'Langston Hullot',
    number: '8591489535',
    location: null,
  },
  {
    restaurant_name: 'Satterfield-Windler',
    owner_name: 'Mace Boddam',
    number: '5616209181',
    location: null,
  },
  {
    restaurant_name: "Price, Marvin and O'Kon",
    owner_name: 'Kacey Stroban',
    number: '9609738541',
    location: null,
  },
  {
    restaurant_name: 'Monahan, Rolfson and Vandervort',
    owner_name: 'Karalee Murrigans',
    number: '3619799086',
    location: 'Apt 1378',
  },
  {
    restaurant_name: 'Thompson Group',
    owner_name: 'Clemmie Bastard',
    number: '8414363833',
    location: null,
  },
  {
    restaurant_name: 'Zemlak Inc',
    owner_name: 'Lydia Pluck',
    number: '2944629879',
    location: null,
  },
  {
    restaurant_name: 'Donnelly LLC',
    owner_name: 'Dario Heinzel',
    number: '3212648826',
    location: 'Suite 92',
  },
  {
    restaurant_name: 'Metz and Sons',
    owner_name: 'Ivett Bill',
    number: '5475274083',
    location: null,
  },
  {
    restaurant_name: 'Prosacco, Haag and Adams',
    owner_name: 'Paige Frostdicke',
    number: '9413958513',
    location: 'Suite 54',
  },
  {
    restaurant_name: 'Predovic LLC',
    owner_name: 'Jilli Nye',
    number: '3473519529',
    location: null,
  },
  {
    restaurant_name: 'Hammes Inc',
    owner_name: 'Geoffry Morsley',
    number: '7993196688',
    location: null,
  },
  {
    restaurant_name: 'Baumbach LLC',
    owner_name: 'Kirsteni Blezard',
    number: '7126321404',
    location: 'PO Box 37338',
  },
  {
    restaurant_name: 'Rosenbaum Group',
    owner_name: 'Baryram Gibling',
    number: '4723858003',
    location: '14th Floor',
  },
  {
    restaurant_name: 'Stamm Inc',
    owner_name: 'Jaymee Cescot',
    number: '2963133276',
    location: 'Suite 14',
  },
  {
    restaurant_name: 'Farrell Inc',
    owner_name: 'Farrell Milch',
    number: '1317108950',
    location: null,
  },
  {
    restaurant_name: 'Durgan-Heidenreich',
    owner_name: 'Hester Pieters',
    number: '4207803308',
    location: null,
  },
  {
    restaurant_name: 'Boyer LLC',
    owner_name: 'Onofredo Walkinshaw',
    number: '8505649916',
    location: null,
  },
  {
    restaurant_name: 'Tillman, Powlowski and Zieme',
    owner_name: 'Boone Ralston',
    number: '8129431718',
    location: 'Suite 26',
  },
  {
    restaurant_name: 'Hermann and Sons',
    owner_name: 'Corinna Gare',
    number: '3327149198',
    location: null,
  },
  {
    restaurant_name: 'Keebler-Johns',
    owner_name: 'Carie Bestwall',
    number: '9183581292',
    location: null,
  },
  {
    restaurant_name: 'Harber-Brown',
    owner_name: "Stavros O'Toole",
    number: '7105226789',
    location: 'Suite 94',
  },
  {
    restaurant_name: 'Schneider, Gleichner and Wolf',
    owner_name: 'Concettina Skala',
    number: '3001888801',
    location: '10th Floor',
  },
  {
    restaurant_name: 'Champlin Inc',
    owner_name: 'Petronilla Woodes',
    number: '3362585884',
    location: null,
  },
  {
    restaurant_name: 'Ritchie LLC',
    owner_name: 'Simonette Riccione',
    number: '7737781419',
    location: null,
  },
  {
    restaurant_name: 'Effertz, Fahey and Labadie',
    owner_name: 'Miquela Scarisbrick',
    number: '7263065490',
    location: null,
  },
  {
    restaurant_name: 'Klocko, Beier and Fadel',
    owner_name: 'Delilah Castles',
    number: '8995801537',
    location: null,
  },
  {
    restaurant_name: 'Monahan-Hauck',
    owner_name: 'Isa Robrow',
    number: '8509535664',
    location: 'PO Box 32516',
  },
  {
    restaurant_name: 'Becker-MacGyver',
    owner_name: 'Aldous Beldham',
    number: '5693375495',
    location: null,
  },
  {
    restaurant_name: 'Fay-Macejkovic',
    owner_name: 'Julee Gavozzi',
    number: '3222893684',
    location: null,
  },
  {
    restaurant_name: 'Feil Group',
    owner_name: 'Merralee Burdett',
    number: '4294437302',
    location: null,
  },
  {
    restaurant_name: 'Maggio-Hartmann',
    owner_name: 'Burl Bangs',
    number: '7089440002',
    location: 'PO Box 13458',
  },
  {
    restaurant_name: 'Morissette, Keeling and Collier',
    owner_name: 'Tammara Dunley',
    number: '7838188611',
    location: 'Room 664',
  },
  {
    restaurant_name: 'Nienow, Bode and Walsh',
    owner_name: 'Marten Seifert',
    number: '8411642105',
    location: null,
  },
  {
    restaurant_name: 'Glover-Reilly',
    owner_name: 'Obed Daine',
    number: '3334117146',
    location: 'PO Box 33052',
  },
  {
    restaurant_name: 'Bashirian-Gibson',
    owner_name: 'Dorise Cambridge',
    number: '6088574436',
    location: null,
  },
  {
    restaurant_name: 'Lang-Franecki',
    owner_name: 'Addi Doddemeade',
    number: '7799164540',
    location: 'Suite 55',
  },
  {
    restaurant_name: "Crooks-D'Amore",
    owner_name: 'Chicky Tassell',
    number: '7758583539',
    location: 'Apt 765',
  },
  {
    restaurant_name: 'Hyatt, Cartwright and Miller',
    owner_name: 'Almeta Ecob',
    number: '8247367259',
    location: null,
  },
  {
    restaurant_name: 'Johnson LLC',
    owner_name: 'Zoe Brucker',
    number: '6305373761',
    location: null,
  },
  {
    restaurant_name: 'Bechtelar, Wiegand and Kozey',
    owner_name: 'Carol-jean Riall',
    number: '1001227086',
    location: 'Room 522',
  },
  {
    restaurant_name: 'Ruecker LLC',
    owner_name: 'Jacquette McQuillen',
    number: '1497230967',
    location: '19th Floor',
  },
  {
    restaurant_name: 'Cassin, Auer and Streich',
    owner_name: 'Xenos Wevell',
    number: '1488698928',
    location: 'Suite 80',
  },
  {
    restaurant_name: 'Tromp-Lubowitz',
    owner_name: 'Flory Cornejo',
    number: '1368977864',
    location: '12th Floor',
  },
  {
    restaurant_name: 'Murphy-Farrell',
    owner_name: 'Helge Champion',
    number: '2607569915',
    location: null,
  },
  {
    restaurant_name: 'Haag Inc',
    owner_name: 'Deerdre Haythorn',
    number: '8462580688',
    location: '11th Floor',
  },
  {
    restaurant_name: 'Brakus Group',
    owner_name: 'Alica Tinsey',
    number: '4863203371',
    location: null,
  },
  {
    restaurant_name: 'Prosacco-Pagac',
    owner_name: 'Ike Colam',
    number: '7189372250',
    location: 'Suite 75',
  },
  {
    restaurant_name: 'Ankunding, Leuschke and Tremblay',
    owner_name: 'Elita Dickey',
    number: '4276472644',
    location: 'Apt 386',
  },
  {
    restaurant_name: 'Ferry, Greenfelder and Harvey',
    owner_name: 'Ivor Ferrulli',
    number: '9539357715',
    location: null,
  },
  {
    restaurant_name: 'Gutmann, Johnston and Luettgen',
    owner_name: 'Renell Geillier',
    number: '3053592133',
    location: 'Apt 1389',
  },
  {
    restaurant_name: 'VonRueden-Ward',
    owner_name: 'Ivar Cohen',
    number: '3196404299',
    location: 'PO Box 1724',
  },
  {
    restaurant_name: 'Blanda, Kuhlman and Hansen',
    owner_name: 'Lorna Laird-Craig',
    number: '3824471739',
    location: '4th Floor',
  },
  {
    restaurant_name: 'Heidenreich Group',
    owner_name: 'Flynn Claypool',
    number: '9899766464',
    location: null,
  },
  {
    restaurant_name: 'Graham Group',
    owner_name: 'Hedwiga Bush',
    number: '1722235134',
    location: null,
  },
  {
    restaurant_name: 'Wisoky-Sawayn',
    owner_name: 'Alis Chimienti',
    number: '1758329257',
    location: '20th Floor',
  },
  {
    restaurant_name: 'Quigley-Orn',
    owner_name: 'Toby Tuison',
    number: '1934699467',
    location: 'Room 1347',
  },
  {
    restaurant_name: 'Marks, Smith and Prohaska',
    owner_name: 'Ad Coxon',
    number: '3587332304',
    location: null,
  },
  {
    restaurant_name: 'Reichert-Heller',
    owner_name: 'Walt Prestage',
    number: '6948171699',
    location: 'Suite 11',
  },
  {
    restaurant_name: 'Abbott Inc',
    owner_name: 'Florenza Gravestone',
    number: '2481898368',
    location: null,
  },
  {
    restaurant_name: 'Mayer, Jacobson and Bruen',
    owner_name: 'Marne Duckitt',
    number: '1334668029',
    location: 'PO Box 53673',
  },
  {
    restaurant_name: 'Lakin-Howe',
    owner_name: 'Matty Gibby',
    number: '6922409551',
    location: null,
  },
  {
    restaurant_name: 'Kris, Stehr and Stiedemann',
    owner_name: 'Pedro Pettegree',
    number: '6003691024',
    location: null,
  },
  {
    restaurant_name: 'Dare-Herman',
    owner_name: 'Jocelyn Paten',
    number: '5449605553',
    location: null,
  },
  {
    restaurant_name: 'Lemke-Ritchie',
    owner_name: 'Rosmunda Targett',
    number: '9142621626',
    location: 'Suite 16',
  },
  {
    restaurant_name: 'Bailey-Hamill',
    owner_name: 'Franny Dubble',
    number: '2157589479',
    location: null,
  },
  {
    restaurant_name: 'Thompson Group',
    owner_name: 'Ana Goscomb',
    number: '7879796868',
    location: null,
  },
  {
    restaurant_name: 'Ward-Mosciski',
    owner_name: 'Tova Meenehan',
    number: '4481204912',
    location: null,
  },
  {
    restaurant_name: 'Reichel, Medhurst and Bernhard',
    owner_name: 'Audre Brownett',
    number: '3059180603',
    location: '6th Floor',
  },
  {
    restaurant_name: 'Klocko-Hilll',
    owner_name: 'Ludvig Dur',
    number: '7299215575',
    location: 'Apt 185',
  },
  {
    restaurant_name: 'Pagac, Barton and Wiegand',
    owner_name: 'Lin Wedge',
    number: '7287599786',
    location: null,
  },
  {
    restaurant_name: 'Windler LLC',
    owner_name: 'Demetris Bogace',
    number: '9353360639',
    location: null,
  },
  {
    restaurant_name: 'Gusikowski-Little',
    owner_name: 'Quill Abisetti',
    number: '3209414512',
    location: 'Suite 72',
  },
  {
    restaurant_name: 'Lakin-Romaguera',
    owner_name: 'Estelle Hebblethwaite',
    number: '3488272281',
    location: '15th Floor',
  },
  {
    restaurant_name: 'Lehner, Homenick and Lubowitz',
    owner_name: 'Ally Gillian',
    number: '7945141352',
    location: null,
  },
  {
    restaurant_name: 'Walsh-Fadel',
    owner_name: 'Matthaeus St Quenin',
    number: '7091719572',
    location: null,
  },
  {
    restaurant_name: 'Grant, Mosciski and Wuckert',
    owner_name: 'Odele Cristofori',
    number: '6182458001',
    location: 'Apt 729',
  },
  {
    restaurant_name: 'Crooks-Torp',
    owner_name: 'Yevette Gaskall',
    number: '4364195623',
    location: '20th Floor',
  },
  {
    restaurant_name: 'Welch and Sons',
    owner_name: 'Modesta Scullion',
    number: '4145154269',
    location: 'PO Box 11219',
  },
  {
    restaurant_name: "Maggio, Kuhic and O'Reilly",
    owner_name: 'Ame Jovicic',
    number: '3172966332',
    location: null,
  },
  {
    restaurant_name: 'Baumbach, Glover and Langworth',
    owner_name: 'Jehanna Batha',
    number: '5011243678',
    location: '17th Floor',
  },
  {
    restaurant_name: 'Langosh, McKenzie and Larkin',
    owner_name: 'Maddie Ferrolli',
    number: '3688722687',
    location: null,
  },
  {
    restaurant_name: 'Bauch, Williamson and Batz',
    owner_name: 'Darby Shave',
    number: '2403593718',
    location: 'PO Box 9754',
  },
  {
    restaurant_name: 'Treutel-Weber',
    owner_name: 'Verne Gyorffy',
    number: '7057076031',
    location: 'Suite 3',
  },
  {
    restaurant_name: 'Torphy, Fadel and Harvey',
    owner_name: 'Glynn Lantuff',
    number: '1187548872',
    location: null,
  },
  {
    restaurant_name: 'Satterfield Inc',
    owner_name: 'Rod Albisser',
    number: '6914268498',
    location: null,
  },
  {
    restaurant_name: 'Roberts, Wolff and Moore',
    owner_name: 'Fonsie Carletti',
    number: '6144284833',
    location: null,
  },
  {
    restaurant_name: 'Rath-Lowe',
    owner_name: 'Vaclav Britto',
    number: '8853862165',
    location: 'PO Box 8678',
  },
  {
    restaurant_name: 'Feeney and Sons',
    owner_name: 'Nita Rodenburgh',
    number: '3007963578',
    location: null,
  },
  {
    restaurant_name: 'Gislason-Flatley',
    owner_name: 'Milty Nadin',
    number: '7307009268',
    location: null,
  },
  {
    restaurant_name: 'Goodwin, Purdy and Hackett',
    owner_name: 'Karry Feavyour',
    number: '1328216448',
    location: 'PO Box 43616',
  },
  {
    restaurant_name: 'Nitzsche-Marquardt',
    owner_name: 'Sarge Leivers',
    number: '1367602871',
    location: 'Room 1195',
  },
  {
    restaurant_name: 'Strosin Group',
    owner_name: 'Kurt Baert',
    number: '1718433365',
    location: null,
  },
  {
    restaurant_name: 'Anderson-Ortiz',
    owner_name: 'Alessandro Feenan',
    number: '6893376453',
    location: null,
  },
  {
    restaurant_name: 'Schowalter, Senger and Marvin',
    owner_name: 'Hervey Bernt',
    number: '6022144864',
    location: 'Apt 964',
  },
  {
    restaurant_name: 'White and Sons',
    owner_name: 'Bradly Wyman',
    number: '9891475657',
    location: '6th Floor',
  },
  {
    restaurant_name: 'Denesik-Mayert',
    owner_name: 'Byrann Andersch',
    number: '5713360119',
    location: 'Suite 58',
  },
  {
    restaurant_name: 'Kuhlman-Kreiger',
    owner_name: 'Floria Noads',
    number: '9806657208',
    location: null,
  },
  {
    restaurant_name: "Pfeffer, O'Hara and Mitchell",
    owner_name: 'Baldwin McKean',
    number: '6213916334',
    location: 'Room 1856',
  },
  {
    restaurant_name: 'Goodwin-Stamm',
    owner_name: 'Yovonnda Drewry',
    number: '2847763818',
    location: null,
  },
  {
    restaurant_name: 'Senger LLC',
    owner_name: 'Garrott Hanington',
    number: '3349965264',
    location: null,
  },
  {
    restaurant_name: 'Boyle-Runte',
    owner_name: 'Leesa Guillou',
    number: '9696224208',
    location: null,
  },
  {
    restaurant_name: 'Muller and Sons',
    owner_name: 'Rebeca Tournay',
    number: '5237520013',
    location: 'PO Box 16119',
  },
  {
    restaurant_name: 'Wehner LLC',
    owner_name: 'Sayres Hurrell',
    number: '7195849772',
    location: '14th Floor',
  },
  {
    restaurant_name: 'Wunsch Group',
    owner_name: 'Marylynne Vasilmanov',
    number: '1763624086',
    location: 'Suite 76',
  },
  {
    restaurant_name: 'Parker-Brown',
    owner_name: 'Eliot Rickaby',
    number: '9106600568',
    location: '16th Floor',
  },
  {
    restaurant_name: 'Pfannerstill LLC',
    owner_name: 'Yolanda Greening',
    number: '3562279964',
    location: null,
  },
  {
    restaurant_name: 'Kuhn, Cartwright and Turcotte',
    owner_name: 'Niki Murrell',
    number: '5571202077',
    location: null,
  },
  {
    restaurant_name: 'Weimann Inc',
    owner_name: 'Patty Arnaldy',
    number: '2202866545',
    location: null,
  },
  {
    restaurant_name: 'Mitchell-Hammes',
    owner_name: 'Zonnya Lillicrop',
    number: '7194312073',
    location: '16th Floor',
  },
  {
    restaurant_name: 'Hoppe-Lang',
    owner_name: 'Olia Medd',
    number: '8224132475',
    location: null,
  },
  {
    restaurant_name: 'Doyle and Sons',
    owner_name: 'Ollie Thompson',
    number: '7633183389',
    location: null,
  },
  {
    restaurant_name: 'Reynolds, McLaughlin and Becker',
    owner_name: 'Janean Duffield',
    number: '1835291071',
    location: 'PO Box 26395',
  },
  {
    restaurant_name: 'Green, Gorczany and Parisian',
    owner_name: 'Nonah Vitte',
    number: '4334458055',
    location: 'Room 1586',
  },
  {
    restaurant_name: 'Mueller-Fisher',
    owner_name: 'Klara Martyn',
    number: '3885390679',
    location: 'Room 651',
  },
  {
    restaurant_name: 'Schowalter and Sons',
    owner_name: 'Portia Burchfield',
    number: '6367165993',
    location: null,
  },
  {
    restaurant_name: 'Crist, Hackett and Maggio',
    owner_name: 'Carver Wareham',
    number: '5681958274',
    location: 'Suite 52',
  },
  {
    restaurant_name: 'Hessel, Altenwerth and Torphy',
    owner_name: 'Kristoffer Coghlin',
    number: '8477085899',
    location: null,
  },
  {
    restaurant_name: 'Maggio Inc',
    owner_name: 'Elaina Strange',
    number: '4276924049',
    location: 'PO Box 75983',
  },
  {
    restaurant_name: 'Schroeder, Schoen and Hauck',
    owner_name: 'Hersch Chippindall',
    number: '7256456287',
    location: null,
  },
  {
    restaurant_name: 'Barton, Klocko and Waelchi',
    owner_name: 'Danica Nund',
    number: '1548183051',
    location: null,
  },
];
